In [17]:
import numpy as np
from IPython.display import  display

### Упражнение 1

На одном графике изобразите время затраченное на вычисление с использованием массивов numpy и стандартных списков в питоне.  
Для более точных результатов замеряйте время выполнения функции несколько раз и усредняйте. 
* Используйте функцию `z = 2*x**2 + 4*y`
* Перемножение матриц размера n на n

### Упражнение 2
* Создайте массив чисел от 2 до 75. Выведите только нечётные. 
* Присвойте нечётным числам этого массива значение -1.



In [507]:
a = np.arange(2,76)
display(a)

j = np.arange(1,75, 2)

display(a[j])

a[j] = -1

display(a)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
       70, 71, 72, 73, 74, 75])

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69,
       71, 73, 75])

array([ 2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16, -1, 18,
       -1, 20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1, 34, -1,
       36, -1, 38, -1, 40, -1, 42, -1, 44, -1, 46, -1, 48, -1, 50, -1, 52,
       -1, 54, -1, 56, -1, 58, -1, 60, -1, 62, -1, 64, -1, 66, -1, 68, -1,
       70, -1, 72, -1, 74, -1])

### Упражнение 3

* Найдите в документации функцию, которая удаляет из одного массива элементы, которые есть в другом. 
* Приведите примеры использования.

In [252]:
a = np.array([0, 1, 2, 5, 0])
b = [0, 2]

display(a)
display(b)

mask = np.in1d(a, b, invert=False)
display(mask)

display(a[mask])

mask = np.in1d(a, b, invert=True)
display(mask)

a[mask]


array([0, 1, 2, 5, 0])

[0, 2]

array([ True, False,  True, False,  True], dtype=bool)

array([0, 2, 0])

array([False,  True, False,  True, False], dtype=bool)

array([1, 5])

### Упражнение 4

* Создайте случайную квадратную матрицу случайного размера от 10 до 100. 
* Найдите максимум и сумму элементов.
* Поделите каждый элемент матрицы на максимум.
* Отнимите от каждой строки матрицы среднее по строке.
* Замените максимальное значение на -1.

In [77]:
#Создайте случайную квадратную матрицу случайного размера от 10 до 100.
a = np.random.randint(10, 101, size = (10, 10))
print (a)

#Найдите максимум и сумму элементов.
print('max -',a.max(),'sum -',a.sum())

#Поделите каждый элемент матрицы на максимум.
display(a / a.max())

#Отнимите от каждой строки матрицы среднее по строке.
b = np.mean(a, axis = 1)
b = b.reshape(len(b),1 )
print (b)
a = a - b
print (a)

#Замените максимальное значение на -1.
print(a.max())
a[a == a.max()] = -1
#display(np.sort(a, kind='quicksort'))
print (a)

[[73 30 74 17 69 91 44 39 58 10]
 [19 15 64 11 44 18 99 45 33 83]
 [63 26 86 69 74 20 63 84 88 96]
 [75 97 77 24 83 82 94 27 40 81]
 [39 60 52 31 88 85 81 86 26 61]
 [82 55 42 27 69 71 76 59 87 56]
 [74 22 60 31 60 78 29 40 61 60]
 [95 56 19 42 60 58 35 11 68 18]
 [10 24 31 37 65 87 35 74 77 75]
 [57 26 60 31 84 38 29 69 68 92]]
max - 99 sum - 5564


array([[ 0.73737374,  0.3030303 ,  0.74747475,  0.17171717,  0.6969697 ,
         0.91919192,  0.44444444,  0.39393939,  0.58585859,  0.1010101 ],
       [ 0.19191919,  0.15151515,  0.64646465,  0.11111111,  0.44444444,
         0.18181818,  1.        ,  0.45454545,  0.33333333,  0.83838384],
       [ 0.63636364,  0.26262626,  0.86868687,  0.6969697 ,  0.74747475,
         0.2020202 ,  0.63636364,  0.84848485,  0.88888889,  0.96969697],
       [ 0.75757576,  0.97979798,  0.77777778,  0.24242424,  0.83838384,
         0.82828283,  0.94949495,  0.27272727,  0.4040404 ,  0.81818182],
       [ 0.39393939,  0.60606061,  0.52525253,  0.31313131,  0.88888889,
         0.85858586,  0.81818182,  0.86868687,  0.26262626,  0.61616162],
       [ 0.82828283,  0.55555556,  0.42424242,  0.27272727,  0.6969697 ,
         0.71717172,  0.76767677,  0.5959596 ,  0.87878788,  0.56565657],
       [ 0.74747475,  0.22222222,  0.60606061,  0.31313131,  0.60606061,
         0.78787879,  0.29292929,  0.4040404 

[[ 50.5]
 [ 43.1]
 [ 66.9]
 [ 68. ]
 [ 60.9]
 [ 62.4]
 [ 51.5]
 [ 46.2]
 [ 51.5]
 [ 55.4]]
[[ 22.5 -20.5  23.5 -33.5  18.5  40.5  -6.5 -11.5   7.5 -40.5]
 [-24.1 -28.1  20.9 -32.1   0.9 -25.1  55.9   1.9 -10.1  39.9]
 [ -3.9 -40.9  19.1   2.1   7.1 -46.9  -3.9  17.1  21.1  29.1]
 [  7.   29.    9.  -44.   15.   14.   26.  -41.  -28.   13. ]
 [-21.9  -0.9  -8.9 -29.9  27.1  24.1  20.1  25.1 -34.9   0.1]
 [ 19.6  -7.4 -20.4 -35.4   6.6   8.6  13.6  -3.4  24.6  -6.4]
 [ 22.5 -29.5   8.5 -20.5   8.5  26.5 -22.5 -11.5   9.5   8.5]
 [ 48.8   9.8 -27.2  -4.2  13.8  11.8 -11.2 -35.2  21.8 -28.2]
 [-41.5 -27.5 -20.5 -14.5  13.5  35.5 -16.5  22.5  25.5  23.5]
 [  1.6 -29.4   4.6 -24.4  28.6 -17.4 -26.4  13.6  12.6  36.6]]
55.9
[[ 22.5 -20.5  23.5 -33.5  18.5  40.5  -6.5 -11.5   7.5 -40.5]
 [-24.1 -28.1  20.9 -32.1   0.9 -25.1  -1.    1.9 -10.1  39.9]
 [ -3.9 -40.9  19.1   2.1   7.1 -46.9  -3.9  17.1  21.1  29.1]
 [  7.   29.    9.  -44.   15.   14.   26.  -41.  -28.   13. ]
 [-21.9  -0.9  -8.9 -

### Упражнение 5
* Напишите функцию, которая берет многомерный вещественный массив с пропущенными значениями (np.nan) и возвращает его копию с заполненными пропусками (заменять средним значением всех элементов массива). Если в массиве одни пропущенные значения, заполните их нулями.

In [163]:
def replace_nan_in_arr(a):
    if np.nansum(a) == 0:
        a[np.isnan(a)] = 0
    else:
        a[np.isnan(a)] = np.nanmean(a)
    return a
        
a =  np.array(np.arange(1, 13, 1).reshape(4, 3), dtype='float')
b = np.arange(1, 5, 2).reshape(2, )
a[b] = np.nan

#a = np.array([[[1,2,np.nan],[3,4,np.nan]],[[1,2,np.nan],[7,5,np.nan]],[[1,2,np.nan],[7,5,np.nan]]])
#a = np.array([[[np.nan,np.nan,np.nan],[np.nan,np.nan,np.nan]],[[np.nan,np.nan,np.nan],[np.nan,np.nan,np.nan]],[[np.nan,np.nan,np.nan],[np.nan,np.nan,np.nan]]])
#a = np.full(5, np.nan)
print(a)
replace_nan_in_arr(a)

a

[[  1.   2.   3.]
 [ nan  nan  nan]
 [  7.   8.   9.]
 [ nan  nan  nan]]


array([[ 1.,  2.,  3.],
       [ 5.,  5.,  5.],
       [ 7.,  8.,  9.],
       [ 5.,  5.,  5.]])

### Упражнение 6
* Напишите функцию которая нормализирует заданный numpy-массив, так чтобы его значения лежали в интервале $[0, 1]$.

In [296]:
def m_f (a):
    t_shape = a.shape
    a[np.isnan(a)] = 0
    a = a.ravel()
    a = (a - a.min() )/(a.max() - a.min())
    #a = np.sort(a, kind='quicksort')
    a = a.reshape(t_shape)
    return a

a = np.random.randint(90, 1500, size = (1,5,3))
m_f(a)




array([[[ 0.57863248,  0.37008547,  0.05897436],
        [ 0.92905983,  0.4957265 ,  0.5982906 ],
        [ 0.69487179,  0.88717949,  0.67863248],
        [ 1.        ,  0.85726496,  0.35384615],
        [ 0.82820513,  0.38376068,  0.        ]]])

### Упражнение 7
* Запишите numpy-array в файл.
* Считайте numpy-array из файла.

In [261]:
#апишите numpy-array в файл.
a = np.arange(12).reshape(3, 4)
print(a)
np.save('example_1', a)

#Считайте numpy-array из файла.
a = np.load('example_1.npy')
a

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Упражнение 8
* Создайте случайный массив
* Найдите в массиве элемент ближайший к данному

In [519]:
#Создайте случайный массив
A = 10 * np.eye(3) + np.random.rand(3, 3)
B = np.random.randint(0, 10, size=A.shape)
print(B)


[[1 8 2]
 [8 7 8]
 [6 3 0]]


In [520]:
#Найдите в массиве элемент ближайший к данному
def my_func(i,a):
    if np.nansum(a[a>=i]) == 0:
        num1 = a.max()
    else:
        num1 = a[a>=i].min() 
        
    if np.nansum(a[a<=i]) == 0:
        num2 = a.min()
    else:
        num2 = a[a<=i].max()
        
    if num1 - i == i - num2:
        if num1 == num2:
            return num1
        else:
            return num1, num2
    elif num1 - i > i - num2:
        return num2
    else:
        return num1
    
my_func(9,B)    

8

### Упражнение 9

* Напишите функцию, которая возвращает  $n \times m$ целочисленную матрицу с заданным значением на границах матрицы и с заданным значением внутри

In [518]:
n=5
m=4

if n > 1 and m > 1:
    a = 1 #граница
    c = 2 #внутри матрицы
    B = np.random.randint(0, 10, size=(n-2,m-2))
    B[:] = c 
    C = np.random.randint(a,a+1,size = (n-2,1))
    B = np.concatenate([B,C], axis=1)
    B = np.concatenate([C,B], axis=1)
    C = np.random.randint(a,a+1,size = (1,m))
    B = np.concatenate([C,B], axis=0)
    B = np.concatenate([B,C], axis=0)
    print(B)
else:
    print ('матрица должна иметь больше одной строки и одного столбца!')


[[1 1 1 1]
 [1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]
 [1 1 1 1]]


### Упражнение 10
* Напишите функцию, которая сортирует строки данной матрицы по значениям заданного столбца в порядке убывания. 

In [537]:
def super_sort(a,i):
    res = a[a[:, i].argsort()[::-1]] 
    return res    
a= np.random.randint(1, 101, (5,5))
print(a)
super_sort (a,2)

[[ 8 89 75 50 64]
 [63 58 85 67 94]
 [77 13 39 87 76]
 [65  9 91 39 95]
 [21 56 13 36 47]]


array([[65,  9, 91, 39, 95],
       [63, 58, 85, 67, 94],
       [ 8, 89, 75, 50, 64],
       [77, 13, 39, 87, 76],
       [21, 56, 13, 36, 47]])

### Упражнение 11

* Напишите функцию, которая создает двоичную матрицу шахматной доски с заданным shape

Пример 4x4:
```python
[[0, 1, 0, 1],
 [1, 0, 1, 0],
 [0, 1, 0, 1],
 [1, 0, 1, 0]]
```

In [539]:
t_shape = 4
if t_shape % 2 ==0:
    a=np.array(([1,0]*int(t_shape/2)+[0,1]*int(t_shape/2))*int(t_shape/2)).reshape(t_shape,t_shape)    
    print(a)

[[1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]


In [547]:
def checkerboard(shape):
    return np.indices(shape).sum(axis=0) % 2
checkerboard((9,4))

array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1]], dtype=int32)

### Упражнение 12
* Напишите игру [life](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life), используя массивы numpy.
* Визуализируйте интерактивно ее результаты.

